export const litterPrueba = [
    {
        displayNameEditors: [],
        uidEditors: [],
        idMother: null,
        uidMother: null,
        idFather: null,
        uidFather: null,
        stages: [
            {
                title: 'Monta',
                state: false,
                date: null,
                male: null,
            },
            {
                title: 'Palpación',
                state: false,
                date: null,
                approximateDate: null,
            },
            {
                title: 'Preparto',
                state: false,
                date: null,
                approximateDate: null,
            },
            {
                title: 'Parto',
                state: false,
                lives: null,
                deaths: null,
                total: null,
                homogen: null,
                date: null,
                news: null,
                approximateDate: null,
            },
            {
                title: 'Destete',
                state: false,
                approximateDate: null,
                date: null,
                WeanedPups: null,
                MaleHatchlings: null,
                FemaleHatchlings: null,
                LitterWeight: null,
            },
        ],
    },
];
