export const litter = [
    {
        id: 124,
        editors: [123, 124],
        state: true,
        idMother: 123456,
        stages: [
            {
                title: 'Monta',
                state: null,
                date: '20-12-2022',
                males: [1234, 1223],
            },
            {
                title: 'Palpación',
                state: true,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                realDate: 21 - 12 - 2022,
            },
            {
                title: 'Preparto',
                state: true,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                realDate: 21 - 12 - 2022,
            },
            {
                title: 'Parto',
                state: true,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                lives: 20,
                deaths: 2,
                stageWeigth: '8000gr',
                homogen: 2,
                total: 24,
                realDate: '21-12-2022',
            },
            {
                title: 'Destete',
                state: false,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                total: 24,
                averageWeight: '1000gr',
                realDate: '21-12-2022',
            },
        ],
    },
    {
        id: 123,
        editors: [123, 124],
        state: false,
        idMother: 123456,
        stages: [
            {
                title: 'Monta',
                state: true,
                date: '20-12-2022',
                males: [1234, 1223],
            },
            {
                title: 'Palpacion',
                state: true,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                realDate: 21 - 12 - 2022,
            },
            {
                title: 'Preparto',
                state: true,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                realDate: 21 - 12 - 2022,
            },
            {
                title: 'Parto',
                state: true,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                lives: 20,
                deaths: 2,
                stageWeigth: '8000gr',
                homogen: 2,
                total: 24,
                realDate: '21-12-2022',
            },
            {
                title: 'Destete',
                state: false,
                approximateDate: '20-12-2022',
                date: '20-12-2022',
                total: 24,
                averageWeight: '1000gr',
                realDate: '21-12-2022',
            },
        ],
    },
];

export const litterPrueba = [
    {
        id: null,
        editors: [],
        state: true,
        idMother: null,
        stages: [
            {
                title: 'Monta',
                state: null,
                date: null,
                male: null,
            },
            {
                title: 'Palpación',
                state: null,
                date: null,
                approximateDate: null,
            },
            {
                title: 'Preparto',
                state: null,
                date: null,
                approximateDate: null,
            },
            {
                title: 'Parto',
                state: null,
                lives: null,
                deaths: null,
                total: null,
                homogen: null,
                date: null,
                stageWeigth: null,
                approximateDate: null,
            },
            {
                title: 'Destete',
                state: null,
                approximateDate: null,
                date: null,
                total: null,
                averageWeight: null,
            },
        ],
    },
];
